import React, { useState, useEffect, useRef } from 'react';
import { Room, RoomEvent, Track } from 'livekit-client';
import Header from './components/Header';
import VoiceControlPanel from './components/VoiceControlPanel';
import VisualWorkspace from './components/VisualWorkspace';
import FeedbackModal from './components/FeedbackModal';

// The agent publishes diagrams, manifests and cards under this data topic.
const VISUAL_TOPIC = 'visual';

export default function App() {
  const [isConnected, setIsConnected] = useState(false);
  const [isConnecting, setIsConnecting] = useState(false);
  const [isMuted, setIsMuted] = useState(false);
  const [selectedSubject, setSelectedSubject] = useState("Kubernetes & Container Orchestration");
  const [sessionId, setSessionId] = useState("");
  const [visualPayloads, setVisualPayloads] = useState([]);
  const [transcripts, setTranscripts] = useState([]);
  const [isFeedbackOpen, setIsFeedbackOpen] = useState(false);

  const roomRef = useRef(null);
  const API_BASE = import.meta.env.VITE_BACKEND_URL || 'http://localhost:8000';

  useEffect(() => {
    if (roomRef.current && isConnected) {
      roomRef.current.localParticipant.setMicrophoneEnabled(!isMuted);
    }
  }, [isMuted, isConnected]);

  const handleStartSession = async () => {
    setIsConnecting(true);
    setVisualPayloads([]);
    setTranscripts([]);

    try {
      // The room name and participant identity are generated by the backend,
      // so the client cannot pick which room it joins.
      const res = await fetch(`${API_BASE}/api/token`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ subject: selectedSubject })
      });

      if (!res.ok) throw new Error('Token generation failed');
      const data = await res.json();
      setSessionId(data.room_name);

      const room = new Room({
        adaptiveStream: true,
        dynacast: true,
      });

      roomRef.current = room;

      room.on(RoomEvent.DataReceived, (payload, _participant, _kind, topic) => {
        if (topic !== VISUAL_TOPIC) return;
        try {
          const visual = JSON.parse(new TextDecoder().decode(payload));
          setVisualPayloads(prev => [...prev, visual]);
        } catch (e) {
          console.warn('Visual payload parse error:', e);
        }
      });

      room.on(RoomEvent.TrackSubscribed, (track) => {
        if (track.kind === Track.Kind.Audio) {
          const audioEl = track.attach();
          document.body.appendChild(audioEl);
          audioEl.play().catch(e => console.warn('Audio autoplay warning:', e));
        }
      });

      room.on(RoomEvent.TrackUnsubscribed, (track) => {
        if (track.kind === Track.Kind.Audio) {
          track.detach().forEach(el => el.remove());
        }
      });

      // Segments are keyed by id and updated in place. Merging by speaker
      // instead would overwrite the previous line whenever the same speaker
      // starts a new segment, losing everything they said before it.
      // The agent already strips visual tags, so the text arrives clean.
      room.on(RoomEvent.TranscriptionReceived, (segments, participant) => {
        const role = participant?.identity === room.localParticipant?.identity ? 'user' : 'tutor';

        setTranscripts(prev => {
          const next = [...prev];
          segments.forEach(segment => {
            const text = (segment.text || '').trim();
            if (!text) return;
            const entry = { id: segment.id, role, text, final: segment.final };
            const idx = next.findIndex(t => t.id === segment.id);
            if (idx === -1) next.push(entry);
            else next[idx] = entry;
          });
          return next;
        });
      });

      room.on(RoomEvent.Disconnected, () => {
        setIsConnected(false);
      });

      await room.connect(data.livekit_url, data.token);
      await room.localParticipant.setMicrophoneEnabled(true);

      setIsConnected(true);
    } catch (e) {
      console.error("Connection error:", e);
      alert("Could not connect to LiveKit voice server. Please verify your LiveKit credentials in .env.");
    } finally {
      setIsConnecting(false);
    }
  };

  const handleEndSession = async () => {
    if (roomRef.current) {
      roomRef.current.disconnect();
      roomRef.current = null;
    }
    setIsConnected(false);
    setIsFeedbackOpen(true);
  };

  const handleSubmitFeedback = async (feedbackData) => {
    try {
      await fetch(`${API_BASE}/api/session/${sessionId}/feedback`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(feedbackData)
      });
    } catch (e) {
      console.error("Feedback submit error:", e);
    }
  };

  return (
    <div className="app-container">
      <Header 
        isConnected={isConnected} 
        selectedSubject={selectedSubject} 
        setSelectedSubject={setSelectedSubject} 
      />

      <main className="main-workspace">
        <VoiceControlPanel 
          isConnected={isConnected}
          isMuted={isMuted}
          setIsMuted={setIsMuted}
          onStartSession={handleStartSession}
          onEndSession={handleEndSession}
          isConnecting={isConnecting}
        />

        <VisualWorkspace 
          visualPayloads={visualPayloads} 
          transcripts={transcripts} 
        />
      </main>

      <FeedbackModal 
        isOpen={isFeedbackOpen}
        onClose={() => setIsFeedbackOpen(false)}
        onSubmitFeedback={handleSubmitFeedback}
        sessionId={sessionId}
      />
    </div>
  );
}
